### ISSUE TITLE
[WidescreenMode] Darstellung von Medienansicht in neuem Tab fehlerhaft

### ISSUE THREAD

**Issue by veekoon** [FlorianMaak/p0weruser#14]
## Allgemeine Informationen
**Browser:** Firefox nightly

**Version:** 0.7.4

**Modul:** Widescreen Modus

## Fehlerbeschreibung
> Hotlinks führen zu fehlerhaften Darstellung der Webseite
![grafik](https://user-images.githubusercontent.com/9080129/35182757-f1cd4fca-fdda-11e7-993e-0be663e5404d.png)

## Aktuelles Verhalten
> Bild verschiebt sich nach oben links, während die Kommentare nach unten rechts verschoben werden. Die Tags und das votingsystem sind mittig.

## Erwartetes Verhalten
> Normale Darstellung

## Reproduzierbarkeit
> Hotlink zu einem Kommentar, z.b. http://pr0gramm.com/top/2341317:comment19781807 in einem neuen Tab öffnen

edit: ich merke gerade, der Fehler kommt auch bei hotlinks zu Bildern zustande, sobald man hotlinks zu Bildern im neuen Tab öffnet.

**Comment by FlorianMaak** [comment]
Das Problem ist **bereits bekannt**, der Fix jedoch nicht ohne weiteres möglich. Der Bug ist mir bereits seit einer Weile ein Dorn im Auge. Ich kann aktuell jedoch nicht sagen, wann ich das schaffe.

Der Fehler tritt **immer** auf, wenn eine Medien-URL in einem Tab im Hintergrund aufgerufen wird. Alle anderen Seiten sind nicht betroffen. Hier hilft temporär nur ein Neuladen der Seite mittels `STRG+F5`

**Comment by FlorianMaak** [comment]
Fixed with https://github.com/FlorianMaak/p0weruser/commit/9351b3640fbaff8dcea112fb3aae121031aa53f0
