### ISSUE TITLE
Klick auf Bild schließt nach zoom nicht

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#15]
## Allgemeine Informationen
**Browser:** Chrome|Firefox
Chrome 65.0.3325.181
**Version:** Version des UserScripts
0.7.9
**Modul:** WidescreenMode

## Fehlerbeschreibung
> Wenn ich auf den Viererpfeil unter dem Vergrößerungsplus drücke, kann ich das Bild/Video nicht mehr mit einem Klick auf das Selbige schliessen und muss entweder das Bild wechseln oder wieder das Logo, Neu, Beliebt oder irgendwas anderes klicken
## Aktuelles Verhalten
> Egal ob "gezommed" oder nicht, das Bild lässt sich nicht mehr weg klicken.
## Erwartetes Verhalten
> Wenn man nach dem Klick auf den Viererpfeil auf das Bild klickt müsste es wieder zu gehen
## Reproduzierbarkeit
> Einfach auf den Viererpfeil klicken und versuchen das Bild zu schliessen.

**Comment by Exportforce** [comment]
Feature Requests ausgelagert in eigene Issues.

Und von WSAD auf ESC gehen für die Kellergemeinschaft? Das sind über 0.0001 kalorien die dafür verbraucht werden. Das ist inakzeptabel!

**Comment by FlorianMaak** [comment]
Feature-Request: #16 #17 #18 #19

**Comment by FlorianMaak** [comment]
Fixed with commit https://github.com/FlorianMaak/p0weruser/commit/263dd4b5428cc516db439ce407527401ee763d1c
