### ISSUE TITLE
Benisanzeige auf Thumbnails

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#17]
Es wäre super praktisch wenn man auf den Thumbnails schon die Benisanzeige sehen könnte, sowohl auf der Seite als auch auf Profilen. Wäre gut, wenn man mal wirklich nur ein paar beliebte Sachen durchgucken will oder erst gar keine -100+ Posts aufzumachen und natürlich für das eigene Ego auf der eigenen Profilseite den Post mit den meisten Benis fix zu finden.

**Comment by FlorianMaak** [comment]
Ich befürchte, dass "beliebt" da drunter leiden könnte. Viele Bilder werden so nicht mehr angeschaut und landen erst gar nicht dort. Ebenso wird die eigene Entscheidung durch die Votes der Masse manipuliert.

**Comment by Exportforce** [comment]
Beliebt würde darunter keinesfalls leiden. Beliebt sind Bilder oft aus gutem Grund und der Pr0 User wird das sehen wollen. Mein Zahlenkommentar war auf Posts mit (nur Beispiel) -100 Votings und mehr ausgeblendet werden können. Es gäbe keinen wirklichen Grund Posts nicht einblenden zu wollen die guten Content haben. Das einzige was leiden würde, wenn es soetwas gäbe, wäre eine Sparte in der die beschissensten Posts gesammelt werden. Diese gibt es aber nicht und daher irrelevant.

**Comment by FlorianMaak** [comment]
Auch dieses Feature habe ich erst einmal unter Vorbehalt eingebaut.
Fährst du mit der Maus über ein Thumb, so sieht man in Stream-Ansichten nun den Benis unten/links in der Ecke.

**Comment by veekoon** [comment]
Funktioniert leider nicht richtig, denn sobald die funktion aus ist, wird innerhalb der bilder kein sfw/nsfw usw. mehr angezeigt.

**Comment by FlorianMaak** [comment]
Weil das im selben Modul sitzt. Gesonderte Einstellungen für Einzelfeatures habe ich mir für das Wochenende vorgenommen.

Es funktioniert aktuell wie gedacht.

**Comment by veekoon** [comment]
Meh. Irgendwie ist das doch doof. Wie soll ich nen OP flamen, wenn ich gar nicht sehe was er getagged hat? :/
Ausserdem, ich stehe deiner Meinung bei: ich glaube es hemmt mehr auf ein Bild zu klicken, wenn man den heiligen Benis im vorfeld schon sieht.

**Comment by FlorianMaak** [comment]
Das sieht man ohne UserScript auch nur anhand der Tags ;)

Da ich schon seit einer Weile Modulbasierte Einstellungen haben möchte, werde ich mich dem Thema wohl mal annehmen. Da stelle ich es den Usern dann frei, welche der drei Markierungen (Filter in Detailansicht, Filter in Stream und/oder Benis in Stream) er aktiviert. Aktuell ist das ganze ja noch recht starr, sodass man nur das "Komplettpaket" hat oder gar nichts.

**Comment by FlorianMaak** [comment]
Dann wird es wohl Zeit, dass ich mich an die Einstellungen setze. (Wird denke ich Morgen oder Übermorgen passieren). Da du dich nicht oft meldest, fasse ich das mal als Lob auf :)

Das ist eig. von nichts abhängig. Das Ganze wird Clientside realisiert und sollte eig. auch von nichts abhängig sein. (Das ist mir sehr wichtig. Habe z.B. auch das Problem, dass ich keinen Überblick über die Zahl der Installationen habe, da ich keine weitere externe Kommunikation wünsche - Datenschutz und so) Das Feature hat aber auch nicht gerade die beste Genauigkeit.

Ich schaue mir das noch an, bevor ich einen neuen Release baue dann. Du nutzt Firefox?

**Comment by veekoon** [comment]
Jojo, bis jetzt ist alles tutti :D 
Die Zahl der Nutzer steigt... ob du das willst, weiß ich nicht(?), wäre aber verwunderlich wenn nicht. Ich glaube aber es spricht nichts dagegen, einen counter einzubauen. Nicht umbedingt Google Analytics, aber irgendwas, dass dir auch ein wenig hilft den Überblick zu behalten.
Jau, ich nutze Firefox, aber bin wieder auf dem stable build nachdem der Nightly ständig abgeschmiert ist.

**Comment by FlorianMaak** [comment]
Installiere mal [diese Version](https://github.com/FlorianMaak/p0weruser/raw/263dd4b5428cc516db439ce407527401ee763d1c/dist/p0weruser.user.js) über deine aktuelle drüber. Das ist der letzte Stand, bevor ich den Benis eingeführt habe. Somit kannst du wenigstens weiter unterwegs sein, ohne was befürchten zu müssen :)

GA/GTM oder Piwik gehen mir zu weit. Ich denke, dass ich den Usernamen clientside hashen werde und diesen Hash dann zu meinem Server schicke (um Dubletten zu vermeiden). Würde das aber als Opt-In gestalten, die User also entscheiden lassen ob sie in die Zählstatistik wollen oder nicht. - Habe vorher aber noch andere Baustellen. Wäre nur ein "nice to have" für mich selbst und hat absolut keine Priorität.

**Comment by veekoon** [comment]
Ich danke. :)

Klingt alles supi. Weitermachen! :D

**Comment by FlorianMaak** [comment]
@veekoon Ich habe für die Filter schon mal Einstellungen eingebaut. Diese finden sich im aktuellen Release.

**Comment by veekoon** [comment]
Sau gut, danke dir!
![grafik](https://user-images.githubusercontent.com/9080129/38470723-513eb5ce-3b67-11e8-832e-1ca81df5e08c.png)
Hier fehlt ein 'r' in Filter :) musst jetzt aber nicht extra updaten :D
