### ISSUE TITLE
SFW, NSFW, NSFL und NSFP Tags auf den Thumbnails

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#18]
Vielleicht nicht direkt als "NSFW" als Wort-Tag auf dem Bild, aber z. B. ein kleiner farbiger Punkt in der Ecke des Thumbnails oder ein dünner 1px Rahmen als Markierung.

**Comment by FlorianMaak** [comment]
Ich werde beide Varianten mal als Dummy basteln und hier dann ein Bild zur Kommunikation hochladen. Ich vermute jedoch, dass ich die Tickets frühestens zum Wochenende abgearbeitet bekomme.

**Comment by Exportforce** [comment]
Kann ich das irgendwie als fertiges runterladen oder muss ich alle änderungen manuell kopieren ?

**Comment by FlorianMaak** [comment]
Einfach auf dem pr0 in die Einstellungen, dann auf "Addons" und unten auf "Beta installieren". Die Version über die bestehende drüberinstallieren.

**Comment by Exportforce** [comment]
Die Variante mit den Dreiecken sieht echt gut aus und ist nicht störend. Super!

**Comment by FlorianMaak** [comment]
Dann werde ich sie heute Abend noch auf die Profilseite (Die Detailansichten der Uploads/Favoriten können das schon) ausweiten.

**Comment by FlorianMaak** [comment]
Ich schaue mir mal an, wie das so ankommt. Dann weite ich das ggf. aus!
