### ISSUE TITLE
Posts mit vorher festgelegten Tags hervorheben.

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#19]
So wie z. B. Reposts hervorgehoben sind wäre es toll, wenn man sich ein paar kleine Taggruppen festlegen könnte die extra hervorgehoben sind oder vielleicht sogar welche um bestimmten Content zu verstecken.

Meine Idee wäre da z. B. dass man bis zu 5? Gruppen festlegen kann in denen man Tags eintragen kann, wie immer mit Komma getrennt, und dann auswählen kann "Hervorheben" oder "Verstecken". Beim Hervorheben vielleicht ähnlich wie bei der Idee zur Markierung für SFW/NSFW/etc halt in einer anderen Ecke des Thumbnails. So dass man z. B. Schmusekadser ausblenden lassen kann, dafür aber z. B. "Kadse", "Bellkadse" in einer Farbe/Markierung und "Schöne Brüste" in einer anderen.

Dabei muss einfach nur ein Tag der Gruppe vorhanden sein um es zu markieren.

**Comment by FlorianMaak** [comment]
Etwas ähnliches habe ich bereits für die "erweiterte Suche" mit angedacht. Hier sollen die Filter "Ausschließen, Einschließen, Min/Max-Benis etc." in Vorlagen abgelegt werden, damit sie für eine neue Suche direkt zur Verfügung stehen. - Das könnte man dann noch auf "markieren" anstatt "filtern" abändern. Technisch ist das jedoch etwas schwierig, was das Markieren angeht.

Das Problem bei der Umsetzung des Markierens ist, dass die Tags nicht mit in der Response der Übersicht enthalten sind. Somit ist für jedes Bild ein eigenes Request notwendig, was das pr0 zu sehr unter Last stellt. Bei 1-2 Filtern mag das noch verkraftbar sein (wie beim Repost-Feature aktuell), sobald es jedoch mehr (mit unterschiedlichen Farben) werden, erzeugt das Script eine ungeheure Last auf dem Server, die ich in der aktuellen Situation nicht zumuten möchte.

**Comment by FlorianMaak** [comment]
Lässt sich mit den gegebenen Daten nicht umsetzen, ohne die Server unnötig zu belasten!

Feature wird nicht umgesetzt!
