### ISSUE TITLE
[WidescreenMode] Möglichkeit ein Bild zu schließen mit der Maus?

### ISSUE THREAD

**Issue by Gamewalker** [FlorianMaak/p0weruser#24]
## Allgemeine Informationen
**Browser:** Chrome
**Version:** 0.9.5

Hallo,
ich benutze das Addon gerade zum ersten mal. Gibt es eine Möglichkeit die Bilder im Overlay per Maus zu schließen? Ich muss immer ESC drücken und das hält total auf. Ich scrolle selten durch alle Bilder durch und öffne immer nur spezifische Bilder und komme dann nicht wieder zurück.

**Comment by FlorianMaak** [comment]
Ein Klick auf das Bild schließt das Medium bei dir nicht?

**Comment by Gamewalker** [comment]
Ok, auf einem 4k Monitor hat man sehr wenig Bild und viel schwarz, ich hab immer auf dem schwarz rumgehämmert und da passiert nix. Kannst du den Background auch in das close event reinpacken?

**Comment by FlorianMaak** [comment]
Das kann ich so umsetzen, ja. Würde aber erst in den nächsten Release mit einfließen.

Für was würdest du dich entscheiden?
- Click auf Background ermöglichen
- Bild vergrößern (Kann ziemlicher Pixelbrei werden, könnte aber ein Icon für die Originalgröße hinzufügen)

**Comment by Gamewalker** [comment]
schließen, schau selten wirklich mal was in groß an :)

**Comment by FlorianMaak** [comment]
Okay. Habe mir das mal für den nächsten Release vorgemerkt.
Ich vermute, dass ich den innerhalb der nächsten Woche veröffentlichen werde.

Sobald das Feature im Beta-Branch gelandet ist, lasse ich es dich wissen, damit du testen kannst. (Sollte zeitnah passieren)

**Comment by FlorianMaak** [comment]
Habe das ganze mit https://github.com/FlorianMaak/p0weruser/commit/f35854abef9991a2a18aa2823079d3e425e4a304 ergänzt!

Zum Installieren der Beta kannst du:
- Die Einstellungen öffnen, in den Tab "Addons" wechseln und über "Beta installieren" die Beta installieren
- Die Installation über folgende URL anstoßen: https://github.com/FlorianMaak/p0weruser/raw/develop/dist/p0weruser.user.js

Ich hoffe auf Feedback und würde das Issue ggf. dann schließen oder weitere Änderungen vornehmen.

**Comment by Gamewalker** [comment]
Funktioniert super, danke dafür 👍
