### ISSUE TITLE
Widescreen Mode - Kleiner Feature-Vorschlag

### ISSUE THREAD

**Issue by Robinatus** [FlorianMaak/p0weruser#26]
Ich finde, dass der Widescreen Mode ein super Idee ist und auch toll umgesetzt wurde. Leider fehlt mir eine wirklich wichtiges Feature, weswegen ich den Widescreen Mode aktuell nicht verwende. Vielleicht bin ich auch einfach zu doof sie zu finden..

Und zwar wünsche ich mir die Möglichkeit, das aktuelle Bild "zu schließen". Also dass man auf die Übersicht der Bilder kommt und nicht ein Bild "aufgeklappt" ist. Natürlich könnte man dies über die Links "Neu" oder "Top" erreichen. Nur ist man dann ja nicht an der Stelle des zuletzt geöffneten Bildes.

Ich hoffe es ist verständlich, was ich meine.

**Comment by FlorianMaak** [comment]
Zufällig so wie in https://github.com/FlorianMaak/p0weruser/issues/24 gelöst, oder habe ich deinen Vorschlag falsch verstanden?

**Comment by Robinatus** [comment]
Peinlich. Okay danke!
