### ISSUE TITLE
Kommentar Favoriten hinzufügen

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#30]
Es gibt eine neue Funktion am Pr0 welche vom Power User unterdrückt wird. Es ist jetzt möglich Kommentare zu favoriten hinzugefügt werden. Bitte mit hinzufügen.

**Comment by FlorianMaak** [comment]
Wurde bereits 4-5h vor deinem Issue als Update veröffentlicht: https://github.com/FlorianMaak/p0weruser/commit/f50ad8c29992060a09ff078959190b53333533a3
