### ISSUE TITLE
Icon für Sticky posts

### ISSUE THREAD

**Issue by ninja-butnotthefortniteone** [FlorianMaak/p0weruser#35]
## Allgemeine Informationen
**Browser:** Alle

**Version:** Alle

**Modul:** -

**Description**
> Das Icon für Sticky Posts (siehe https://pr0gramm.com/ die ersten 4 posts) gibt es noch nicht.
Ich find aber die Datei nicht, da es grad 5 uhr ist... :/
![grafik](https://user-images.githubusercontent.com/38287122/41504359-955706e2-71ec-11e8-9b5c-9369c93ce344.png)

**Comment by FlorianMaak** [comment]
Das gab es vor zwei Tagen schon als Update.
