### ISSUE TITLE
Chrome Support Benis Graph

### ISSUE THREAD

**Issue by xXFreeFunXx** [FlorianMaak/p0weruser#36]
## Allgemeine Informationen
**Browser:** Chrome
**Version:** Alle
**Modul:** Pr0p0ll
**Description**
Ob im oder ohne Chrome Store ist mir das eigentlich egal aber hätte das Plugin gerne so im Chrome ohne Script Manager wie Greasemonkey!

Ich glaube da fehlt nur eine manifest.json datei.

Derzeit nutze ich das [Cust0m Pr0gramm](https://github.com/Schwuchtelini/cust0m) Skript von @Schwuchtelini was nicht mehr weiterentwickelt wird aber mir gefällt da die Benis anzeige im Header und am Coolsten der Benis Graph.

**Chrome Support Feature request**
**Benis Graph Feature request**

Grüße
FreeFun

**Comment by FlorianMaak** [comment]
Aktuell ist nicht angedacht, dass das Script als Addon realisiert wird. 

**Das hat die folgenden Hintergründe:**
* Ich will Google keine Zahlungsdaten übermitteln (Was jedoch durch die 5€ Registrierungsgebühr erzwungen wird)
* ich möchte nicht drei Umgebungen maintainen, zumal z.B. Die notification-API anders angesprochen werden muss bei Tampermonkey, verglichen mit nativem JS
* ich möchte keinen so weitreichenden Zugriff auf den Browser haben (Ist nicht notwendig und birgt Risiken)

Die angesprochen Funktionen können übrigens auch so eingebaut werden, da Bedarf es keinem Addon. Für diese beiden aber bitte gesonderte Issues erstellen, damit der Überblick gewahrt wird.
