### ISSUE TITLE
Benis Graph

### ISSUE THREAD

**Issue by xXFreeFunXx** [FlorianMaak/p0weruser#37]
## Allgemeine Informationen
**Browser:** Alle
**Version:** Alle
**Modul:** -
**Description**

Eine Benis Graph anzeige wäre geil, wie beim Cust0m Pr0gramm Plugin.

Hier ein Beispiel:
https://puu.sh/AQuV8/0e7d33f816.gif

Grüße
FreeFun

**Comment by FlorianMaak** [comment]
Wie verhält sich der Graph, wenn der Browser für eine Zeit nicht geöffnet wurde?
Bleibt die Kurve da einfach konstant und hat dann einen Peak, oder was anderes?

Ich könnte hier maximal mit einem ServiceWorker arbeiten, der im Hintergrund weiter läuft. Eine Lösung mit einem Dienst den ich hoste und der das jeden Tag abruft, möchte ich nicht einbinden. (Ich will eure Daten nicht auf meinem Server haben)

**Comment by xXFreeFunXx** [comment]
Du stellst fragen ^^

Also wie es funktioniert kann ich dir natürlich nicht sagen, da schau dir doch das Script von Schwuchtelii an unter https://github.com/Schwuchtelini/cust0m

Aber Lokal weis doch das Script von dir welches Benis stand ich habe und wenn dieser sich verändert!?

**Comment by FlorianMaak** [comment]
Es weiß das nur, wenn der Browser geöffnet ist. (Bei einem Worker ebenso, da muss das pr0 aber nicht geöffnet sein)
In den Code brauche ich nicht schauen. Der ist durch nen Uglyfier gegangen und das tue ich mir nicht an.

**Comment by xXFreeFunXx** [comment]
Wenn ich aber das Script neu installiert habe wusste er vom alten Benis
stand aber nichts mehr.

Ich denke das lässt sich alles Lokal lösen aber da bist du der Fachmann! ;)

Florian <notifications@github.com> schrieb am Mo. 6. Aug. 2018 um 20:04:

**Comment by FlorianMaak** [comment]
Der Graph würde bei mir dann halt nur Tage beinhalten, wo der Browser auch an war. Aber das sollte ja ausreichen mMn.
