### ISSUE TITLE
Benis Anzeige im Header

### ISSUE THREAD

**Issue by xXFreeFunXx** [FlorianMaak/p0weruser#38]
## Allgemeine Informationen
**Browser:** Alle

**Version:** Alle

**Modul:** Pr0p0ll

**Description**
Schau mal ob du das [Bild hier](https://github.com/Schwuchtelini/cust0m/blob/master/benis.png) eher nutzen kannst als das FontAwesome!

Nur ein Vorschlag.

Grüße
FreeFun

**Comment by FlorianMaak** [comment]
Das Icon passt nicht zum Rest der Seite. Darum habe ich mich für FontAwesome entschieden.

**Comment by xXFreeFunXx** [comment]
Ich fand das passte ganz gut, der Benis ist Weiß und der Rest Transparent und auf Schwarzen Hintergrund sah das richtig gut aus. 

Fand schon das es passt, magst du da nicht mal drüber schauen oder es optional gestalten?

Derzeit wirk es als ob man ein Avatar hätte bei Pr0 nur das er nicht vergeben wäre. Sieht einfach doof aus.

**Comment by FlorianMaak** [comment]
Installiere dir mal die neue Beta bitte. 

Änderungen: https://github.com/FlorianMaak/p0weruser/commit/de64c1b75c6897d8979260165d733441a2d07f93
Installation: https://github.com/FlorianMaak/p0weruser/raw/develop/dist/p0weruser.user.js

Das Icon kann über eine eigene Einstellung ein/aus geschaltet werden.

**Comment by FlorianMaak** [comment]
Ich glaube, dass ich die Einstellung noch invertieren werde.
