### ISSUE TITLE
Einklappbarer Kommentar bereich

### ISSUE THREAD

**Issue by xXFreeFunXx** [FlorianMaak/p0weruser#39]
## Allgemeine Informationen
**Browser:** Alle

**Version:** Alle

**Modul:** WidescreenMode

**Description**
Der komplette Kommentar Bereich sollte einklappbar sein, so das man den Post zentral Mittig sieht. Kommt ja auch mal vor, das man nur Post sehen will und weniger in den Kommentar Bereich schauen möchte.

Als optionales Feature natürlich.

Grüße
FreeFun ^^

**Comment by FlorianMaak** [comment]
An den Kommentaren wollte ich sowieso noch was ändern. Das passt ganz gut dazu. Ich weiß nur nicht, wann ich Zeit dafür finde.

**Comment by FlorianMaak** [comment]
Mit https://github.com/FlorianMaak/p0weruser/commit/196d41e241fcddbe12e2ea8341aa9040da115dec ergänzt.
