### ISSUE TITLE
Diverse Suchen markieren alles als repost

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#43]
## Allgemeine Informationen
**Browser:** Chrome|Firefox
Chrome
**Version:** Version des UserScripts
1.0.3
**Modul:** Wenn du weißt, welches Modul das Problem auslöst, so nenne dieses hier.
Repost?
## Fehlerbeschreibung
> Bitte beschreibe den Fehler so genau wie möglich.
https://pr0gramm.com/new/die%20kadse%20schläft%20jetzt%20hier
Alles wird als repost markiert, auch wenn es keiner ist.
## Aktuelles Verhalten
> Wie äußert sich der Fehler? Bzw. was ist das aktuelle Verhalten, was nicht gewünscht ist?
Markiert halt alles als repost
## Erwartetes Verhalten
> Wie sollte sich das Script eig. verhalten? Was läuft in deinen Augen schief?
Nicht alles als repost markieren
## Reproduzierbarkeit
> Wie kann der Fehler repsoruziert werden? (Bzw. Wie kann er hervorgerufen werden?)
https://pr0gramm.com/new/die%20kadse%20schläft%20jetzt%20hier
Einfach draufklicken

**Comment by FlorianMaak** [comment]
Mit Commit https://github.com/FlorianMaak/p0weruser/commit/39b5c72ead1be067efd9b34e1ea5a29649d7977a behoben.
