### ISSUE TITLE
Feature: TinEye Reverse Image Search

### ISSUE THREAD

**Issue by Admonstrator** [FlorianMaak/p0weruser#44]
## Allgemeine Informationen
Die Google Image Suche gibt es bereits, ich würde mir aber auch ein Einbinden der TinEye Suche wünschen, da diese meist bessere Resultate ausspuckt & Quellen zuverlässiger identifiziert.

Suchparameter sind: 
`https://tineye.com/search/?url=[ENCODED IMAGE URL]`

**Comment by FlorianMaak** [comment]
Klingt nach einer guten Idee. Werde ich mit in die nächste Version packen.

**Comment by FlorianMaak** [comment]
Mit https://github.com/FlorianMaak/p0weruser/commit/dd5e365ee416b33b3b05f12d8d3434043bb57897 hinzugefügt. Findet dann seinen Weg in den nächsten Release.
