### ISSUE TITLE
[WidescreenMode] Likebar

### ISSUE THREAD

**Issue by Kamikali** [FlorianMaak/p0weruser#49]
## Allgemeine Informationen
**Browser:** Alle

**Description**
Eine Likebar so wie im Screenshot wäre auch für den Widescreenmode super!
Die Likebar im Bild kommt vom "Extended Benis" script.

![benisbar](https://user-images.githubusercontent.com/6325146/44300281-c5e33a80-a304-11e8-880e-7f5ca365348d.png)

**Comment by FlorianMaak** [comment]
Ich habe deinen Kommentar mal editiert. Bilder bitte immer als Anhang posten, damit sie auch in Zukunft verfügbar bleiben und das Issue nachvollziehbar bleibt. Ich werde das Feature mit Version 1.1.0 dann liefern.

**Comment by FlorianMaak** [comment]
Mit Commit https://github.com/FlorianMaak/p0weruser/commit/daa01995f9b62fb6c9d23d7cc1bdf6b79af954f3 hinzugefügt.

**Comment by Kamikali** [comment]
Danke!
Bin nicht sehr erfahren mit GitHub... sorry für die Umstände.

**Comment by FlorianMaak** [comment]
Mit https://github.com/FlorianMaak/p0weruser/commit/1da0ee57027ba7c4bbd1a969942a7be677a662f2 nun auch im Releasezweig.
