### ISSUE TITLE
Bildscrolling

### ISSUE THREAD

**Issue by veekoon** [FlorianMaak/p0weruser#5]
## Allgemeine Informationen
**Browser:** Chrome|Firefox

**Version:** 0.4.5

Würde gerne, wie früher, durch die Bilder Scrollen können. <3

**Comment by FlorianMaak** [comment]
Meinst du damit, dass sich das Medium nicht via Scroll wechseln lässt, sondern die Medien automatisch gezoomt ausgegeben werden und das Scrollrad dann vertikal das Medium verschiebt?

**Comment by veekoon** [comment]
Das Scrollrad bewirkt bei mir unter FF Nightly gar nichts irgendwie.
Im alten Design, das quasi deinem Breitbildmodus entsprach, konnte man zwischen den posts, der Reihe nach, mit dem Scrollrad durch scrollen. Wenn man nach oben scrollte, bekam man neuere Posts zu sehen, wenn man nach unten scrollt, ältere. Das liese sich bestimmt auch mit deinem Script machen. 
Hinzufügen könnte man unter anderem: Man scrollt als User die letzten 10 ungesehenen Bilder durch, sortiert von alt zu neu. Zeitgleich kommt aber ein neuer Post auf die Top Seite. Wenn sich der User nun bei dem ihm letzten Bild befindet, könnte ein weiteres scrollen ein refresh auslösen. Und falls vorhanden, das nächste, neue Bild laden.
:-)

**Comment by FlorianMaak** [comment]
Unter Chrome funktioniert das bereits genau so (seit der ersten Version). Ich schaue mir heute Abend mal an, wieso es unter Firefox nicht funktioniert. Danke für den Bugreport.

**Comment by veekoon** [comment]
♥

**Comment by FlorianMaak** [comment]
Mit dem neuen Update (0.5.4) sollte das Scrollen in Firefox nun funktionieren.
Den Wunsch mit dem autom. Nachladen der Medienliste habe ich als eigenes Feature-Request isoliert und nehme mir dem an, wenn ich zeit dafür finde. (Aktuell haben Bugs erst Mal vorrang)

https://github.com/FlorianMaak/p0weruser/issues/9

**Comment by veekoon** [comment]
I love dich so hart im Moment 💃
