### ISSUE TITLE
Tags are not loaded/shown in Widescreen Mode

### ISSUE THREAD

**Issue by Frubi22** [FlorianMaak/p0weruser#51]
## Allgemeine Informationen
**Browser:** Tested on Chrome and Opera

**Version:** 1.0.7

**Modul:** Widescreen Mode

## Fehlerbeschreibung
when Widescreen Mode is activated the Page does not load/show any Tags

## Reproduzierbarkeit
activate Widescreen Mode and visit a p0st

**Comment by FlorianMaak** [comment]
I'll fix this today in the evening.
