### ISSUE TITLE
Pixelbrei beim Öffnen eines Videos

### ISSUE THREAD

**Issue by Muschifloete** [FlorianMaak/p0weruser#54]
## Allgemeine Informationen
**Browser:** Firefox

**Version:** 1.0.11

**Modul:** Widescreen

## Fehlerbeschreibung
Wenn man sich durchklickt und bei einem Video landet, dann erscheint zuerst ein Pixelbrei in der Mitte, bevor das Video die eigentliche Größe erreicht. Das war in den vergangenen Versionen anders. Manchmal dauert es ca. 0,5-1 Sekunde, bis sich das Video komplett öffnet und dann startet. 

Beispielfoto: 

![pixelbrei](https://user-images.githubusercontent.com/43032862/46177554-8c163400-c2b3-11e8-9d46-1b6a3355680c.JPG)

## Aktuelles Verhalten
Ladedauer eines Videos liegt zwischen 0,3 und 1 Sekunde. 

## Erwartetes Verhalten
Keine zeitliche Verzögerung beim Laden eines Videos.

**Comment by FlorianMaak** [comment]
"It's not a bug, it's a feature" - Die Funktionalität hat man auf dem pr0 seit kurzem auch ohne p0weruser. 
Ich kann maximal versuchen, dass der Pixelbrei die selbe Größe haben wird, wie das spätere Medium.
