### ISSUE TITLE
Lautstärkebutton, Vergrößerungsbutton und Play-/Pausebutton fehlerhaft

### ISSUE THREAD

**Issue by Muschifloete** [FlorianMaak/p0weruser#55]
## Allgemeine Informationen
**Browser:** Chrome|Firefox

**Version:** 1.0.12

**Modul:** Widescreen

## Fehlerbeschreibung
Im Widescreenmodus ist der Lautstärkebutton nur zur Hälfte zu sehen. Der (anscheinend neu eingeführte) Pausebutton ist nicht zu sehen. Außerdem fehlt der +Button, um das Bild in einem externen Tab in Originalgröße anzuzeigen. Was mir noch aufgefallen ist: das Bild passt sich nicht mehr den Seitenrändern an, wenn man auf das Kreuz mit den 4 Pfeilen klickt, sondern nur noch an den Längskanten oben und unten. Das macht sich v.a. bei sehr langen Posts bemerktbar, weil man sie praktisch nicht wirklich vergrößern kann.

**Comment by FlorianMaak** [comment]
Danke für dein Feedback. Ich versuche das so schnell wie möglich zu fixen, kann aber nicht versprechen dass das heute noch was wird.

**Comment by FlorianMaak** [comment]
- Der Player ist nun mit Version 1.0.13 gefixed
- Das Plus kommt nur, wenn das Bild in einer größeren Version verfügbar ist.
- Das Problem mit dem Resize bekomme ich nicht reproduziert. Bei mir vergrößert es sich und ich kann es bewegen :/

**Comment by Muschifloete** [comment]
Danke. Der Player funktioniert jetzt wieder mit Pausebutton und Lautstärkeregler. 

Das Plus kommt bei mir nur bei manchen Bildern, nicht bei allen, die eigentlich vergrößerbar wären. Mit Rechtsklick und "Grafik anzeigen" erhalte ich in einem externen Tab dann das Bild in Originalgröße.

Für den Resize habe ich das Beispiel hier: https://pr0gramm.com/top/2772123

Wenn ich auf den Resizebutton klicke, dann ist das Bild kaum größer und unlesbar, weil winzig. Es passt sich nicht den Seitenrändern im Widescreenmodus an. Diesbezüglich hätte ich auch noch einen Wunsch: Falls der Button bei mir mal wieder funktionieren sollte, dann wäre es schön, wenn die Scrollgeschwindigkeit etwas höher wäre. V.a. bei sehr, sehr scrollintensiven Posts ist es etwas zu langsam.

**Comment by Muschifloete** [comment]
Nachtrag: das Resizeproblem habe ich wohl nur beim Firefox. Mit Chrome funktioniert es.

**Comment by Muschifloete** [comment]
Der "Fehler" mit dem Plus ist sehr wahrscheinlich kein Fehler. Aber weil das Resize eben nicht funktioniert mit Firefox fühlt es sich bei manchen Bildern so an, als wäre es ein Fehler. Aber ich hab mal zwischen Firefox und Chrome verglichen, da stimmt das mit dem Plus immer überein. Kurzum: es ist kein Fehler. ^^

Danke für Alles.

**Comment by FlorianMaak** [comment]
Möchtest du für die Scrollgeschwindigkeit noch ein Feature-Request einreichen?
Dann würde ich das Issue hier schließen und verliere das dann nicht aus den Augen :)

**Comment by Muschifloete** [comment]
Erledigt. Du kannst den Fall hier zu den Akten legen. :)
