### ISSUE TITLE
Scrollgeschwindigkeit nach Resize

### ISSUE THREAD

**Issue by Muschifloete** [FlorianMaak/p0weruser#58]
## Allgemeine Informationen
**Browser:** Alle

**Version:** Alle

**Modul:** Widescreen

**Description**
Scrollgeschwindigkeit nach dem Resize ist momentan einen Tick zu langsam. Vielleicht könnte man die ein Stückchen erhöhen. Ist vermutlich Geschmackssache, also wären verschiedene Scrollgeschwindigkeitsoptionen sinnvoll.

**Comment by FlorianMaak** [comment]
Mit https://github.com/FlorianMaak/p0weruser/commit/3e242e809d1d885f9a15acfdfce0c451e75d0f7c ergänzt. Die aktuelle Beta beinhaltet dieses Feature bereits.
