### ISSUE TITLE
Bilder/Videos verzerrt oder zu klein im Widescreenmode

### ISSUE THREAD

**Issue by Muschifloete** [FlorianMaak/p0weruser#59]
## Allgemeine Informationen
**Browser:** Chrome|Firefox

**Version:** 1.0.13

**Modul:** Widescreen

## Fehlerbeschreibung
Bilder werden bei **Chrome** entweder zu klein oder verzerrt angezeigt. 

Beispiel:
verzerrt
![verzerrt](https://user-images.githubusercontent.com/43032862/46581395-505c3680-ca38-11e8-9e89-b32080b388c0.JPG)

![verzerrt2](https://user-images.githubusercontent.com/43032862/46581422-a4ffb180-ca38-11e8-951f-666036e5e027.JPG)

korrekte Anzeige in eigenem Tab
![nicht verzerrt](https://user-images.githubusercontent.com/43032862/46581397-57834480-ca38-11e8-9b35-6b92993bf907.JPG)

Videos werden zu klein angezeigt. Als Beispiel dient ein webm im Widescreenmodus, dass die Maße 440x330 Pixel hat. Wenn man es seperat in einem eigenen Tab öffnet, dann hat es die Maße 460x344 Pixel. Der Unterschied mag nicht sehr groß sein, aber bei kleinen Videos ist es schon signifikant. 

Selbiges Fehlverhalten stelle ich im **Firefox** fest, nur dass damit der Resize nicht funktioniert und die Bilder/Videos einfach zu klein angezeigt werden, allerdings nicht verzerrt. 

## Aktuelles Verhalten
Bilder/Videos werden verzerrt oder zu klein angezeigt. 

## Erwartetes Verhalten
Bilder/Videos sollten dieselbe Größe haben wie in einem seperat geöffneten Tab. Anpassung an den Widescreen erst dann, wenn das Bild- oder Videomaterial zu groß ist.

**Comment by FlorianMaak** [comment]
Ich mache mich am Wochenende an die Fehlerbehebung und werde dann ein Update veröffentlichen.
