### ISSUE TITLE
Bewertung wird nicht angezeigt

### ISSUE THREAD

**Issue by Frubi22** [FlorianMaak/p0weruser#6]
## Allgemeine Informationen
**Browser:** Opera&Firefox

**Version:** 0.4.5

**Modul:** Widescreen mode

## Fehlerbeschreibung
Sobald man das Bild verlässt, ist die Bewertung nicht mehr sichtbar, betrifft nur +- aber nicht das Favoriten Herz. Ein erneutes klicken auf die Bewertung oder ein neu laden der Seite führt dazu das das Bild als bewertet angezeigt wird, der Benis wird nicht erneut verändert(d.h. nur die anzeige stimmt nicht)

## Aktuelles Verhalten
 Siehe Fehlerbeschreibung

## Erwartetes Verhalten
Bewertung sollte immer sichtbar sein

## Reproduzierbarkeit
 Auf ein Bild gehen, es bewerten, das Bild wechseln und wieder zurück wechseln

**Comment by FlorianMaak** [comment]
Der Fehler ist bereits bekannt. Das Problem liegt hier im Austausch des Templates. Ich habe mir auch schon eine Lösung überlegt, komme vermutlich aber leider erst zum Wochenende dazu, die offenen Issues abzuarbeiten. Das Problem sollte auch in allen Browsern auftreten.
