### ISSUE TITLE
Bilder werden nicht mehr vergrößert bei click auf den toggleMove Button

### ISSUE THREAD

**Issue by skorpion1298** [FlorianMaak/p0weruser#60]
## Allgemeine Informationen
**Browser:** Firefox

**Version:** 1.0.13

## Fehlerbeschreibung
> Wenn ich einen Post öffne und das Bild ist größer als das es in den Schirm passt und ich versuche herein zu zoomen dann tut sich da nicht viel. Das Bild wird ein wenig vergrößert aber nicht so wie es am Anfang der fall war.

## Aktuelles Verhalten
> Wie äußert sich der Fehler? Bzw. was ist das aktuelle Verhalten, was nicht gewünscht ist?
Standard ansicht beim öffnen des Posts:
![grafik](https://user-images.githubusercontent.com/9423638/47293860-ab328800-d60b-11e8-9316-0facebe1fac7.png)

> Nach dem klick auf den toggleMove Button:
![grafik](https://user-images.githubusercontent.com/9423638/47293921-d4ebaf00-d60b-11e8-913d-9e1f414eb9e2.png)

## Installierte Scripte:
> Meine  Installierten Scripte für pr0 sind p0weruser und pr0gramm Linkvorschau

**Comment by FlorianMaak** [comment]
Ich schaue mir heute Abend mal die Fehler bezüglich der Medienausgabe an.

**Comment by FlorianMaak** [comment]
Mit Version 1.0.14 behoben. https://github.com/FlorianMaak/p0weruser/commit/35b33248a5c22c9dac442177931ed48d42c45fb4
