### ISSUE TITLE
Videos in optimaler größe Abspielen

### ISSUE THREAD

**Issue by skorpion1298** [FlorianMaak/p0weruser#61]
## Allgemeine Informationen
**Browser:** Alle

**Version:** Alle

**Modul:** p0weruser

**Description**
Videos werden je nach Format sehr klein aber auch mal sehr groß dargestellt.
Gibt es eine möglichkeit die Videos prozentuell an den Bildschirm an zu passen aber auch so das kleine Videos nicht verpixeln?

![grafik](https://user-images.githubusercontent.com/9423638/47489664-714dc580-d847-11e8-8d5a-5e8332105054.png)

Auf dem Video hier unter: https://pr0gramm.com/top/2802634 erkennt man fast nichts da es so klein ist.

Vielleicht einen Slider wie bei Google Maps hinzu fügen über den man hinein zoomen kann ins Video oder wie bei den Bildern über einen toggleMove Button.

MfG

**Comment by FlorianMaak** [comment]
Ich mache mich am Wochenende an die Fehlerbehebung und werde dann ein Update veröffentlichen.
