### ISSUE TITLE
Pfeil im Vorschaubild verbugged bei "Bereits gesehen"-Markierung

### ISSUE THREAD

**Issue by Alfondorion** [FlorianMaak/p0weruser#62]
## Allgemeine Informationen
**Browser:** Firefox, Chrome

**Version:** 1.0.14 (wahrscheinlich alle, seitdem Gamb das Design leicht verändert hat)

## Fehlerbeschreibung
> Der kleine, schwarze Pfeil in der Vorschau des aktiven Bildes wird nach oben verschoben.

## Aktuelles Verhalten
> Der Pfeil wird bei aktivierter "Bereits gesehen"-Markierung im Vorschaubild nach oben verschoben und die Box grau eingefärbt.

## Erwartetes Verhalten
> Der Pfeil sollte unten bleiben, wie er ohne die Markierung auch tut.

## Reproduzierbarkeit
> In Chrome ist dasselbe Problem. Anbei ein Bild: https://i.imgur.com/zEkKFWj.png
Auf dem ersten sind alle Vorschaubildmarkierungen, außer "Bereits gesehen" aktiviert. So sollte es eigentlich aussehen.
Auf dem zweiten ist zusätzlich "Bereits gesehen aktiviert"
Auf dem dritten ist das Skript ganz aus.
Auf dem Vierten ist als einzige Option des Skripts "Bereits gesehen" aktiviert.

Somit lässt es sich einzig auf diese Funktion zurück führen.

Danke für die gute Arbeit am Skript, ich nutze es seit einiger Zeit sehr gerne!

**Comment by FlorianMaak** [comment]
Ich mache mich am Wochenende an die Fehlerbehebung und werde dann ein Update veröffentlichen.
