### ISSUE TITLE
Fehlen der Datumsanzeige im Upload

### ISSUE THREAD

**Issue by skorpion1298** [FlorianMaak/p0weruser#66]
## Allgemeine Informationen
**Browser:** Chrome|Firefox

**Version:** 1.0.21

## Fehlerbeschreibung
>Wenn man über das Datum des Uploads fährt, zeigt er nur eine Zahl an und nicht das genaue Datum des Uploads. z.B. "4." oder "27."

## Erwartetes Verhalten
>Wie sollte sich das Script eig. verhalten? Was läuft in deinen Augen schief?
Es sollte den Tag, Monat und eventuell die Uhrzeit des Uploads darstellen.

## Reproduzierbarkeit
>Einfach mit der Maus über ein Uploaddatum fahren und siehe da :)

**Comment by skorpion1298** [comment]
In den Kommentaren sieht man das Datum garnicht.

**Comment by FlorianMaak** [comment]
Mit https://github.com/FlorianMaak/p0weruser/commit/b12464429483d74e5510551e205639d871ca7831 behoben. (In der Beta ist der Fix bereits)
