### ISSUE TITLE
Tag-Voteinfo

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#67]
Ich würde gern sehen wie die Tags gevoted wurden. Ich hab das auf nem Screenshot von nem anderen User mal vor ner Weile gelesen. Da in letzter Zeit von mir viele nützliche Tags ins nichts gevoted werden (Regel 10: Tagvandalismus/Downvotespam) würde ich gern sehen, wie die Tags gevoted wurden, so dass ich eine bessere Übersicht habe ob irgendwo Vandalismus vorliegt.

**Comment by FlorianMaak** [comment]
Finde ich spannend. Hast du mal einen Link?
Diese Information liegt nämlich nicht vor.

**Comment by Exportforce** [comment]
Sorry... das war irgendein random post.
Er hatte bei den tags ein kleines (X/Y) hinter jedem tag. Ist n paar Monate her.
Gab glaub ich sogar was dadrüber in den Kommentaren. Hatte mich damals nicht wirklich gejuckt, weil kein Interessse. Im aktuellen Fall jedoch. Vielleicht gab es die info mal?

Aber wenn das nicht mehr geht, es wird ja zumindest trotzdem einiges an Tags ausgeblendet. Gibt es eine Möglichkeit auszulesen ob tags nur wegen der masse ausgeblendet sind oder weil runtergevoted?

**Comment by Exportforce** [comment]
Wäre es möglich dies mit anzugeben um Tagvandalismus melden zu können?

**Comment by FlorianMaak** [comment]
Das bekommt das pr0 schon selbst ganz gut raus inzwischen. Afaik ist das automatisiert.

**Comment by Exportforce** [comment]
Nur, wenn einer viel downvoted. Wenn einfach 20 Leute sich zusammentun und eine Person runtervoten passiert nichts. Habe mehrere Uploads bei denen Tags versteckt werden. Bei wenig Tags ists klar. Aber bei mehreren nicht mehr. Da wäre eine anzeige echt super geil.
