### ISSUE TITLE
Irgendwas in einem Profil anklicken -> Backbutton

### ISSUE THREAD

**Issue by Exportforce** [FlorianMaak/p0weruser#69]
Wenn man von einem Profil aus irgendetwas anklickt, egal ob Kommentar, Fav oder Post und von der Seite aus den Browser-Back-Button benutzt verschwindet die Scrollmöglichkeit komplett. Weder mit Mausrad, Tastatur noch sonst wie.

**Comment by FlorianMaak** [comment]
Mit https://github.com/FlorianMaak/p0weruser/commit/b0c31d2887a9666f49df48bfde9595817b736c45 behoben. Die Beta-Version beinhaltet diesen Fix bereits.
