### ISSUE TITLE
Token im pr0p0ll Modul anpassen

### ISSUE THREAD

**Issue by RundesBalli** [FlorianMaak/p0weruser#71]
## Allgemeine Informationen
Modul: pr0p0ll Integration

## Fehlerbeschreibung
Das Token für die Abfrage der offenen Umfragen auf pr0p0ll ist [0-9a-f]{64}.
Bitte das Modul so anpassen, dass die Nutzereingabe getrimmt wird (Leerzeichen entfernen) und dass das Token nur akzeptiert wird, wenn die oben genannte Regex zutrifft. Immer wenn das davon abweicht gibts einen Haufen Logeinträge, da der Input Wert nicht passt. Danke!

**Comment by FlorianMaak** [comment]
Wenn meine Sperre aufgehoben wurde, gebe ich das Thema sofort an. Aktuell hält diese noch zwei Wochen.

**Comment by RundesBalli** [comment]
Danke @Robinatus
