### ISSUE TITLE
Dontation Banner out of space in Widescreenmode

### ISSUE THREAD

**Issue by Frubi22** [FlorianMaak/p0weruser#76]
## Allgemeine Informationen
**Browser:** Chrome|Firefox

**Version:** 1.0.24

**Modul:** Widescreen Mode

## Fehlerbeschreibung
Das div mit der id: cancer-donations hat den style position:absolute und left:-120px und ist damit außerhalb des sichtbaren Bereiches, ein ändern auf den wert 170px würde das problem bereits beheben

**Comment by FlorianMaak** [comment]
Mit Version 1.0.25 (https://github.com/FlorianMaak/p0weruser/commit/be61542079e1635caae195045f20bfaae10a1210) behoben.

Da im WidescreenMode auf ``flex`` gesetzt wird, lässt sich das auch ohne absolute Positionierung lösen, sondern durch ``order``. Ich habe das entsprechend gepdated und einen neuen Release veröffentlicht.

Danke für die Fehlermeldung.
