### ISSUE TITLE
Texterkennung

### ISSUE THREAD

**Issue by xXFreeFunXx** [FlorianMaak/p0weruser#90]
## Allgemeine Informationen
**Browser:** Chrome

**Version:** 1.0.26

**Modul:** Texterkennung

## Fehlerbeschreibung
> Er macht aus - einfach ’

## Reproduzierbarkeit
> Bei Keys ist mir das aufgefallen. Hier ein Link zum Reproduzieren:
https://pr0gramm.com/new/3260005

**Comment by FlorianMaak** [comment]
Das ist eine library und durch mich nicht fixbar.
